x-logging: &logging
  logging:
    options:
      max-size: "10m"
      max-file: "3"

x-environment: &env
  environment:
    - TZ=Asia/Krasnoyarsk

services:

  node-builder:
    container_name: moto-rental_node-builder
    image: node:20-alpine
    working_dir: /app
    volumes:
      - "../../frontend:/app:ro"
      - "frontend_dist:/build"
    command: sh -c "npm ci && npm run build && cp -r dist/* /build/"
    <<: *logging

  web:
    container_name: moto-rental_web
    image: nginx:alpine
    <<: *logging
    <<: *env
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "frontend_dist:/var/www/html:ro"
      - "./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    restart: always
    depends_on:
      node-builder:
        condition: service_completed_successfully
      backend:
        condition: service_started
    networks:
      moto_network:
        ipv4_address: 10.10.0.2

  backend:
    container_name: moto-rental_backend
    build:
      context: ../../
      dockerfile: dockerfiles/backend/Dockerfile
      target: prod
    <<: *logging
    <<: *env
    env_file:
      - "../../.env"
    volumes:
      - "backend_data:/data"
    restart: always
    networks:
      moto_network:
        ipv4_address: 10.10.0.3

networks:
  moto_network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

volumes:
  frontend_dist:
  backend_data:
